import Foundation
import SwiftData

// SwiftData models. Local-only store (no CloudKit).
//
// Relationship rule used throughout the app: insert a model into the context first,
// then set its relationships.

enum ItemKind: String, Codable {
    case photo
    case link
    case note
}

@Model
final class TasteCollection {
    var id: UUID = UUID()
    var name: String = ""
    /// What the collection holds, used in statements: "I like [domain] that…" (visuals, reds, rooms, songs).
    var domain: String = "things"
    /// The sense verb for statements: feel, taste, sound, look.
    var verb: String = "feel"
    var symbol: String = "square.stack"
    var createdAt: Date = Date()
    var sortIndex: Int = 0
    /// A written or polished taste statement.
    var statement: String?
    /// `Distillation.signature` at the time `statement` was written; a mismatch means it's stale.
    var statementSignature: String?

    // Imported collections (a Pinterest board) carry a summary instead of individual saves.
    /// `CollectionSource` raw value, or nil for collections made in the app.
    var sourceRaw: String?
    /// The board id at the source, used to refresh in place.
    var sourceID: String?
    var sourceURL: String?
    /// Items at the source when imported (pins on the board).
    var sourceItemCount: Int = 0
    var importedAt: Date?
    /// What the source is about, in Claude's words.
    var summary: String?
    /// JSON-encoded `ImportedProfile`: tag counts over the analyzed items.
    var profileData: Data?
    /// Up to four local image file names standing in for the source, newline-separated.
    var coverImageNamesRaw: String?

    @Relationship(deleteRule: .nullify, inverse: \SaveItem.collection)
    var items: [SaveItem] = []

    init(name: String, domain: String = "things", verb: String = "feel", symbol: String = "square.stack", sortIndex: Int = 0) {
        self.id = UUID()
        self.name = name
        self.domain = domain
        self.verb = verb
        self.symbol = symbol
        self.sortIndex = sortIndex
        self.createdAt = Date()
    }
}

@Model
final class SaveItem {
    var id: UUID = UUID()
    var createdAt: Date = Date()
    var kindRaw: String = ItemKind.photo.rawValue
    var title: String?
    /// Body of a text note, or the text that came with a shared link.
    var note: String?
    var urlString: String?
    var imageFileName: String?
    /// Procedural placeholder art for demo saves (see PlaceholderArt).
    var artStyleRaw: String?
    var artSeed: Int = 0
    /// The answer to "Why did you save this?"
    var why: String?
    /// Set when the user finishes interrogating the save.
    var decodedAt: Date?
    var collection: TasteCollection?

    @Relationship(deleteRule: .cascade, inverse: \TagEntry.item)
    var tags: [TagEntry] = []

    init(kind: ItemKind, title: String? = nil, note: String? = nil, urlString: String? = nil, imageFileName: String? = nil, createdAt: Date = Date()) {
        self.id = UUID()
        self.kindRaw = kind.rawValue
        self.title = title
        self.note = note
        self.urlString = urlString
        self.imageFileName = imageFileName
        self.createdAt = createdAt
    }
}

@Model
final class TagEntry {
    var id: UUID = UUID()
    var name: String = ""
    /// Normalized matching key (TagText.key).
    var key: String = ""
    var levelRaw: String = TagLevel.ingredient.rawValue
    var statusRaw: String = TagStatus.suggested.rawValue
    var sourceRaw: String = TagSource.user.rawValue
    var createdAt: Date = Date()
    var item: SaveItem?

    init(name: String, level: TagLevel, status: TagStatus, source: TagSource) {
        let cleaned = TagText.clean(name)
        self.id = UUID()
        self.name = cleaned
        self.key = TagText.key(cleaned)
        self.levelRaw = level.rawValue
        self.statusRaw = status.rawValue
        self.sourceRaw = source.rawValue
        self.createdAt = Date()
    }
}

/// What was last synced for one row: if the row's current fingerprint differs, it needs uploading;
/// if the row is gone, its deletion does. Cleared on sign-out.
@Model
final class SyncRecord {
    /// "\(table):\(rowID)", or "image:\(fileName)" for uploaded images.
    @Attribute(.unique) var recordKey: String = ""
    var fingerprint: String = ""
    var syncedAt: Date = Date()

    init(recordKey: String, fingerprint: String) {
        self.recordKey = recordKey
        self.fingerprint = fingerprint
        self.syncedAt = Date()
    }
}

/// A Learn card generated by Claude or edited by the user, cached locally.
@Model
final class LearnCardRecord {
    @Attribute(.unique) var key: String = ""
    var payload: Data = Data()
    /// "generated" or "edited".
    var origin: String = "generated"
    var updatedAt: Date = Date()

    init(key: String, content: LearnCardContent, origin: String) {
        self.key = key
        self.payload = (try? JSONEncoder().encode(content)) ?? Data()
        self.origin = origin
        self.updatedAt = Date()
    }

    var content: LearnCardContent? {
        try? JSONDecoder().decode(LearnCardContent.self, from: payload)
    }

    func update(_ content: LearnCardContent, origin: String) {
        payload = (try? JSONEncoder().encode(content)) ?? payload
        self.origin = origin
        updatedAt = Date()
    }
}

// MARK: - Convenience

extension SaveItem {
    var kind: ItemKind { ItemKind(rawValue: kindRaw) ?? .photo }
    var artStyle: ArtStyle? { artStyleRaw.flatMap(ArtStyle.init(rawValue:)) }
    var url: URL? { urlString.flatMap(URL.init(string:)) }
    var isDecoded: Bool { decodedAt != nil }

    var confirmedTags: [TagEntry] {
        tags.filter { $0.status == .confirmed }.sorted { $0.createdAt < $1.createdAt }
    }

    func confirmedTags(_ level: TagLevel) -> [TagEntry] {
        confirmedTags.filter { $0.level == level }
    }

    func suggestedTags(_ level: TagLevel) -> [TagEntry] {
        tags.filter { $0.status == .suggested && $0.level == level }.sorted { $0.createdAt < $1.createdAt }
    }

    /// Any tag (in any state) with this key at this level — used to avoid duplicates and re-suggesting rejects.
    func tag(key: String, level: TagLevel) -> TagEntry? {
        tags.first { $0.key == key && $0.level == level }
    }

    var displayTitle: String {
        if let title, !title.isEmpty { return title }
        if let note, !note.isEmpty { return String(note.prefix(80)) }
        if let host = url?.host() { return host.replacingOccurrences(of: "www.", with: "") }
        switch kind {
        case .photo: return "Photo"
        case .link: return "Link"
        case .note: return "Note"
        }
    }

    var snapshot: ItemSnapshot {
        ItemSnapshot(id: id, tags: confirmedTags.map { TagSnapshot(name: $0.name, level: $0.level) })
    }
}

extension TagEntry {
    var level: TagLevel {
        get { TagLevel(rawValue: levelRaw) ?? .ingredient }
        set { levelRaw = newValue.rawValue }
    }

    var status: TagStatus {
        get { TagStatus(rawValue: statusRaw) ?? .suggested }
        set { statusRaw = newValue.rawValue }
    }

    var source: TagSource { TagSource(rawValue: sourceRaw) ?? .user }

    func rename(_ newName: String) {
        let cleaned = TagText.clean(newName)
        guard !cleaned.isEmpty else { return }
        name = cleaned
        key = TagText.key(cleaned)
    }
}

enum CollectionSource: String {
    case pinterest

    var label: String {
        switch self {
        case .pinterest: "Pinterest"
        }
    }

    /// What the source calls its items.
    func itemNoun(_ count: Int) -> String {
        switch self {
        case .pinterest: count == 1 ? "pin" : "pins"
        }
    }
}

extension TasteCollection {
    var sortedItems: [SaveItem] { items.sorted { $0.createdAt > $1.createdAt } }

    var distillation: Distillation { effectiveDistillation(items: items) }

    var source: CollectionSource? { sourceRaw.flatMap(CollectionSource.init(rawValue:)) }
    var isImported: Bool { source != nil }

    var importedProfile: ImportedProfile? {
        get { profileData.flatMap { try? JSONDecoder().decode(ImportedProfile.self, from: $0) } }
        set { profileData = newValue.flatMap { try? JSONEncoder().encode($0) } }
    }

    var coverImageNames: [String] {
        get { (coverImageNamesRaw ?? "").split(separator: "\n").map(String.init) }
        set { coverImageNamesRaw = newValue.isEmpty ? nil : newValue.joined(separator: "\n") }
    }

    /// The saves in this collection distilled, plus the imported summary when there is one.
    /// Pass `items` when the caller already has them filtered (views observe saves via @Query).
    func effectiveDistillation(items: [SaveItem]) -> Distillation {
        let fromSaves = Distiller.distill(items.map(\.snapshot))
        guard let profile = importedProfile else { return fromSaves }
        return Distillation(profile: profile).merged(with: fromSaves)
    }

    /// Renames (or merges) an imported tag, as the Pantry does for saves.
    func renameImportedTag(key: String, level: TagLevel, to newName: String) {
        guard var profile = importedProfile else { return }
        let cleaned = TagText.clean(newName)
        guard !TagText.key(cleaned).isEmpty else { return }
        profile.update(level) { counts in
            for index in counts.indices where TagText.key(counts[index].name) == key { counts[index].name = cleaned }
        }
        importedProfile = profile
    }

    func removeImportedTag(key: String, level: TagLevel) {
        guard var profile = importedProfile else { return }
        profile.update(level) { counts in counts.removeAll { TagText.key($0.name) == key } }
        importedProfile = profile
    }

    /// Imported tags as pantry usages: one "item" per collection, so the Pantry and Learn cards see them.
    var importedUsages: [TagUsage] {
        guard let profile = importedProfile else { return [] }
        return TagLevel.allCases.flatMap { level in
            profile.counts(for: level).map { TagUsage(name: $0.name, level: level, itemID: id, collectionName: name) }
        }
    }

    /// The statement to show: the written one while it still matches the collection, else the live template.
    func currentStatement(for distillation: Distillation) -> (text: String?, isWritten: Bool) {
        if let statement, !statement.isEmpty, statementSignature == distillation.signature {
            return (statement, true)
        }
        return (TasteStatement.template(domain: domain, verb: verb, distillation: distillation), false)
    }

    var stub: CollectionStub { CollectionStub(id: id, name: name, symbol: symbol) }
}

extension ModelContext {
    /// Adds a confirmed or suggested tag to an item unless one with the same key and level exists.
    @discardableResult
    func addTag(_ name: String, level: TagLevel, to item: SaveItem, status: TagStatus = .confirmed, source: TagSource = .user) -> TagEntry? {
        let cleaned = TagText.clean(name)
        let key = TagText.key(cleaned)
        guard !key.isEmpty else { return nil }
        if let existing = item.tag(key: key, level: level) {
            // Typing a tag the AI suggested (or one you rejected earlier) confirms it.
            if status == .confirmed, existing.status != .confirmed { existing.status = .confirmed }
            return existing
        }
        let tag = TagEntry(name: cleaned, level: level, status: status, source: source)
        insert(tag)
        tag.item = item
        return tag
    }
}
